/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/todo": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todo.id"];
          created_at?: parameters["rowFilter.todo.created_at"];
          name?: parameters["rowFilter.todo.name"];
          user_id?: parameters["rowFilter.todo.user_id"];
          done?: parameters["rowFilter.todo.done"];
          due_date?: parameters["rowFilter.todo.due_date"];
          repeat_frequency?: parameters["rowFilter.todo.repeat_frequency"];
          by_day?: parameters["rowFilter.todo.by_day"];
          by_month?: parameters["rowFilter.todo.by_month"];
          by_month_day?: parameters["rowFilter.todo.by_month_day"];
          by_time?: parameters["rowFilter.todo.by_time"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["todo"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** todo */
          todo?: definitions["todo"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todo.id"];
          created_at?: parameters["rowFilter.todo.created_at"];
          name?: parameters["rowFilter.todo.name"];
          user_id?: parameters["rowFilter.todo.user_id"];
          done?: parameters["rowFilter.todo.done"];
          due_date?: parameters["rowFilter.todo.due_date"];
          repeat_frequency?: parameters["rowFilter.todo.repeat_frequency"];
          by_day?: parameters["rowFilter.todo.by_day"];
          by_month?: parameters["rowFilter.todo.by_month"];
          by_month_day?: parameters["rowFilter.todo.by_month_day"];
          by_time?: parameters["rowFilter.todo.by_time"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todo.id"];
          created_at?: parameters["rowFilter.todo.created_at"];
          name?: parameters["rowFilter.todo.name"];
          user_id?: parameters["rowFilter.todo.user_id"];
          done?: parameters["rowFilter.todo.done"];
          due_date?: parameters["rowFilter.todo.due_date"];
          repeat_frequency?: parameters["rowFilter.todo.repeat_frequency"];
          by_day?: parameters["rowFilter.todo.by_day"];
          by_month?: parameters["rowFilter.todo.by_month"];
          by_month_day?: parameters["rowFilter.todo.by_month_day"];
          by_time?: parameters["rowFilter.todo.by_time"];
        };
        body: {
          /** todo */
          todo?: definitions["todo"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  todo: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
    /** Format: uuid */
    user_id: string;
    /**
     * Format: boolean
     * @default false
     */
    done: boolean;
    /** Format: timestamp with time zone */
    due_date?: string;
    /** Format: text */
    repeat_frequency?: string;
    /** Format: smallint */
    by_day?: number;
    /** Format: smallint */
    by_month?: number;
    /** Format: smallint */
    by_month_day?: number;
    /** Format: time with time zone */
    by_time?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description todo */
  "body.todo": definitions["todo"];
  /** Format: bigint */
  "rowFilter.todo.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.todo.created_at": string;
  /** Format: text */
  "rowFilter.todo.name": string;
  /** Format: uuid */
  "rowFilter.todo.user_id": string;
  /** Format: boolean */
  "rowFilter.todo.done": string;
  /** Format: timestamp with time zone */
  "rowFilter.todo.due_date": string;
  /** Format: text */
  "rowFilter.todo.repeat_frequency": string;
  /** Format: smallint */
  "rowFilter.todo.by_day": string;
  /** Format: smallint */
  "rowFilter.todo.by_month": string;
  /** Format: smallint */
  "rowFilter.todo.by_month_day": string;
  /** Format: time with time zone */
  "rowFilter.todo.by_time": string;
}

export interface operations {}

export interface external {}
